import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const languages = [
  { code: 'hi', name: 'हिन्दी', label: 'Hindi' },
  { code: 'en', name: 'English', label: 'English' },
  { code: 'gu', name: 'ગુજરાતી', label: 'Gujarati' },
  { code: 'ta', name: 'தமிழ்', label: 'Tamil' },
  { code: 'te', name: 'తెలుగు', label: 'Telugu' },
  { code: 'bn', name: 'বাংলা', label: 'Bengali' },
  { code: 'mr', name: 'मराठी', label: 'Marathi' }
];

export const translations = {
  en: {
    title: 'JanSahay AI',
    subtitle: 'Government Scheme Assistant',
    tagline: 'Find Government Schemes in Your Language',
    searchPlaceholder: 'Search schemes by name, keyword or ask a question...',
    browseCategories: 'Browse Categories',
    featuredSchemes: 'Featured Schemes',
    howItWorks: 'How It Works',
    step1Title: 'Ask AI',
    step1Desc: 'Type or speak your question in your regional language.',
    step2Title: 'Get Instant Info',
    step2Desc: 'Get clear eligibility rules and document checklists.',
    step3Title: 'Apply Officially',
    step3Desc: 'Navigate directly to the official government portal to apply.',
    navHome: 'Home',
    navBrowse: 'Browse Schemes',
    navEligibility: 'Check Eligibility',
    navApplications: 'My Applications',
    navDashboard: 'Dashboard',
    navAbout: 'About',
    navChat: 'Ask Assistant',
    login: 'Login',
    signup: 'Sign Up',
    disclaimer: 'JanSahay AI is an independent open-source project and is not affiliated with or endorsed by the Government of India. Always verify details on the official portals.',
    statisticsTitle: 'Platform Impact',
    statSchemes: 'Total Schemes Indexed',
    statPortals: 'Official Portals Covered',
    statLanguages: 'Languages Supported',
    allRightsReserved: 'All rights reserved.',
    applyNow: 'Apply on Official Portal',
    knowMore: 'Know More',
    source: 'Source',
    relatedSchemes: 'Related Schemes',
    whoQualifies: 'Who Qualifies (Eligibility)',
    docsNeeded: 'Documents Needed',
    howToApply: 'How to Apply (Step-by-Step Guide)',
    aboutMission: 'Our Mission',
    aboutText: 'JanSahay AI aims to bridge the information gap in rural and semi-urban India. By simplifying complex eligibility guidelines and providing information in native languages with simple voice input, we help ensure no eligible citizen is left behind.',
    feedbackHelpful: 'Was this answer helpful?',
    feedbackThankYou: 'Thank you for your feedback!',
    voicePromptStart: 'Listening... Please speak now.',
    voicePromptStop: 'Processing speech...',
    voiceNotSupported: 'Speech recognition is not supported in this browser.',
    ttsSpeak: 'Listen (Text to Speech)',
    ttsStop: 'Stop Listening',
    thinking: 'Thinking, please wait...',
    navCalculator: 'Check Eligibility',
    calcTitle: 'Scheme Eligibility Calculator',
    calcSub: 'Answer a few questions to find which government schemes you qualify for.',
    calcStep1: 'Demographics',
    calcStep2: 'Socio-Economic Profile',
    calcStep3: 'Financial & Education',
    calcAge: 'Age (in years)',
    calcCategory: 'Category (Caste)',
    calcOccupation: 'Primary Occupation',
    calcIncome: 'Annual Family Income (₹)',
    calcTaxpayer: 'Are you an income taxpayer?',
    calcBankAccount: 'Do you have a bank account?',
    calcStudentClass: 'Are you currently a student?',
    calcEligibleTitle: 'Eligible Schemes',
    calcIneligibleTitle: 'Ineligible Schemes',
    calcResultSuccess: 'Based on your profile, you qualify for the following schemes:',
    calcResultNone: 'Based on your profile, you do not qualify for any schemes at this time.',
    calcViewDetails: 'View Details',
    calcApplyNow: 'Apply Now',
    calcIneligibleReason: 'Criteria failed:',
    detectLocation: 'Detect My Location',
    selectLocation: 'Select Location',
    locationNotSupported: 'Geolocation is not supported by your browser.',
    locationPermissionDenied: 'Location permission denied. Please select location manually.',
    locationError: 'Unable to retrieve location.',
    selectState: 'Select State',
    selectDistrict: 'Select District',
    stateDefault: 'All States',
    districtDefault: 'All Districts',
    enquiryOffice: 'Nearest Enquiry Office & Helpdesk',
    helpline: 'Helpline',
    address: 'Address',
    viewOnMap: 'View on Google Maps',
    printSummary: 'Print / Download A4 Summary'
  },
  hi: {
    title: 'जनसहाय AI',
    subtitle: 'सरकारी योजना सहायक',
    tagline: 'अपनी भाषा में सरकारी योजनाएं खोजें',
    searchPlaceholder: 'नाम, कीवर्ड द्वारा खोजें या कोई प्रश्न पूछें...',
    browseCategories: 'श्रेणियां ब्राउज़ करें',
    featuredSchemes: 'प्रमुख योजनाएं',
    howItWorks: 'यह कैसे काम करता है',
    step1Title: 'AI से पूछें',
    step1Desc: 'अपनी क्षेत्रीय भाषा में अपना प्रश्न लिखें या बोलें।',
    step2Title: 'तुरंत जानकारी पाएं',
    step2Desc: 'स्पष्ट पात्रता नियम और आवश्यक दस्तावेजों की सूची प्राप्त करें।',
    step3Title: 'आधिकारिक रूप से आवेदन करें',
    step3Desc: 'आवेदन करने के लिए सीधे आधिकारिक सरकारी पोर्टल पर जाएं।',
    navHome: 'होम',
    navBrowse: 'योजनाएं देखें',
    navEligibility: 'पात्रता जांचें',
    navApplications: 'मेरे आवेदन',
    navDashboard: 'डैशबोर्ड',
    navAbout: 'हमारे बारे में',
    navChat: 'सहायक से पूछें',
    login: 'लॉग इन',
    signup: 'साइन अप',
    disclaimer: 'जनसहाय AI एक स्वतंत्र ओपन-सोर्स प्रोजेक्ट है और यह भारत सरकार से संबद्ध या समर्थित नहीं है। हमेशा आधिकारिक पोर्टल पर विवरण सत्यापित करें।',
    statisticsTitle: 'प्लेटफॉर्म प्रभाव',
    statSchemes: 'कुल अनुक्रमित योजनाएं',
    statPortals: 'कवर किए गए आधिकारिक पोर्टल',
    statLanguages: 'समर्थित भाषाएं',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    applyNow: 'आधिकारिक पोर्टल पर आवेदन करें',
    knowMore: 'और जानें',
    source: 'स्रोत',
    relatedSchemes: 'संबंधित योजनाएं',
    whoQualifies: 'कौन पात्र है (पात्रता)',
    docsNeeded: 'आवश्यक दस्तावेज',
    howToApply: 'आवेदन कैसे करें (चरण-दर-चरण मार्गदर्शिका)',
    aboutMission: 'हमारा उद्देश्य',
    aboutText: 'जनसहाय AI का उद्देश्य ग्रामीण और अर्ध-शहरी भारत में सूचना के अंतर को कम करना है। सरल आवाज इनपुट के साथ देशी भाषाओं में जानकारी प्रदान करके, हम यह सुनिश्चित करने में मदद करते हैं कि कोई भी पात्र नागरिक पीछे न छूटे।',
    feedbackHelpful: 'क्या यह उत्तर मददगार था?',
    feedbackThankYou: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    voicePromptStart: 'सुन रहा है... कृपया अब बोलें।',
    voicePromptStop: 'आवाज को संसाधित किया जा रहा है...',
    voiceNotSupported: 'इस ब्राउज़र में भाषण पहचान समर्थित नहीं है।',
    ttsSpeak: 'सुनें (आवाज में)',
    ttsStop: 'सुनना बंद करें',
    thinking: 'सोच रहा हूँ, कृपया प्रतीक्षा करें...',
    navCalculator: 'पात्रता जांचें',
    calcTitle: 'योजना पात्रता कैलकुलेटर',
    calcSub: 'यह जानने के लिए कि आप किन सरकारी योजनाओं के पात्र हैं, कुछ प्रश्नों के उत्तर दें।',
    calcStep1: 'जनसांख्यिकी',
    calcStep2: 'सामाजिक-आर्थिक प्रोफ़ाइल',
    calcStep3: 'वित्तीय और शिक्षा',
    calcAge: 'आयु (वर्षों में)',
    calcCategory: 'श्रेणी (जाति)',
    calcOccupation: 'मुख्य व्यवसाय',
    calcIncome: 'वार्षिक पारिवारिक आय (₹)',
    calcTaxpayer: 'क्या आप आयकरदाता हैं?',
    calcBankAccount: 'क्या आपके पास बैंक खाता है?',
    calcStudentClass: 'क्या आप वर्तमान में छात्र हैं?',
    calcEligibleTitle: 'पात्र योजनाएं',
    calcIneligibleTitle: 'अपात्र योजनाएं',
    calcResultSuccess: 'आपकी प्रोफ़ाइल के आधार पर, आप निम्नलिखित योजनाओं के लिए पात्र हैं:',
    calcResultNone: 'आपकी प्रोफ़ाइल के आधार पर, आप वर्तमान में किसी भी योजना के लिए पात्र नहीं हैं।',
    calcViewDetails: 'विवरण देखें',
    calcApplyNow: 'अभी आवेदन करें',
    calcIneligibleReason: 'अपात्रता का कारण:',
    detectLocation: 'मेरी स्थिति पहचानें',
    selectLocation: 'स्थान चुनें',
    locationNotSupported: 'आपके ब्राउज़र द्वारा जियोलोकेशन समर्थित नहीं है।',
    locationPermissionDenied: 'स्थान अनुमति अस्वीकार कर दी गई। कृपया मैन्युअल रूप से स्थान चुनें।',
    locationError: 'स्थान प्राप्त करने में असमर्थ।',
    selectState: 'राज्य चुनें',
    selectDistrict: 'जिला चुनें',
    stateDefault: 'सभी राज्य',
    districtDefault: 'सभी जिले',
    enquiryOffice: 'निकटतम पूछताछ कार्यालय और हेल्पडेस्क',
    helpline: 'हेल्पलाइन',
    address: 'पता',
    viewOnMap: 'गूगल मैप्स पर देखें',
    printSummary: 'A4 सारांश प्रिंट / डाउनलोड करें'
  },
  gu: {
    title: 'જનસહાય AI',
    subtitle: 'સરકારી યોજના સહાયક',
    tagline: 'આપની ભાષામાં સરકારી યોજનાઓ શોધો',
    searchPlaceholder: 'નામ, કીવર્ડ દ્વારા શોધો અથવા પ્રશ્ન પૂછો...',
    browseCategories: 'કેટેગરીઝ બ્રાઉઝ કરો',
    featuredSchemes: 'મુખ્ય યોજનાઓ',
    howItWorks: 'તે કેવી રીતે કામ કરે છે',
    step1Title: 'AI ને પૂછો',
    step1Desc: 'તમારી પ્રાદેશિક ભાષામાં તમારો પ્રશ્ન લખો અથવા બોલો.',
    step2Title: 'ત્વરિત માહિતી મેળવો',
    step2Desc: 'સ્પષ્ટ પાત્રતા નિયમો અને દસ્તાવેજોની સૂચિ મેળવો.',
    step3Title: 'સત્તાવાર રીતે અરજી કરો',
    step3Desc: 'અરજી કરવા માટે સીધા સત્તાવાર સરકારી પોર્ટલ પર જાઓ.',
    navHome: 'હોમ',
    navBrowse: 'યોજનાઓ જુઓ',
    navEligibility: 'પાત્રતા ચકાસો',
    navApplications: 'મારી અરજીઓ',
    navDashboard: 'ડેશબોર્ડ',
    navAbout: 'અમારા વિશે',
    navChat: 'સહાયકને પૂછો',
    login: 'લોગ ઈન',
    signup: 'સાઇન અપ',
    disclaimer: 'જનસહાય AI એ એક સ્વતંત્ર ઓપન-સોર્સ પ્રોજેક્ટ છે અને તે ભારત સરકાર સાથે સંલગ્ન કે સમર્થિત નથી. સત્તાવાર પોર્ટલ પર હંમેશા વિગતોની ચકાસણી કરો.',
    statisticsTitle: 'પ્લેટફોર્મ પ્રભાવ',
    statSchemes: 'કુલ ઇન્ડેક્સ કરેલી યોજનાઓ',
    statPortals: 'આવરી લેવામાં આવેલા સત્તાવાર પોર્ટલ',
    statLanguages: 'સમર્થિત ભાષાઓ',
    allRightsReserved: 'સર્વાધિકાર સુરક્ષિત.',
    applyNow: 'સત્તાવાર પોર્ટલ પર અરજી કરો',
    knowMore: 'વધુ જાણો',
    source: 'સ્ત્રોત',
    relatedSchemes: 'સંબંધિત યોજનાઓ',
    whoQualifies: 'કોણ લાયક છે (પાત્રતા)',
    docsNeeded: 'જરૂરી દસ્તાવેજો',
    howToApply: 'કેવી રીતે અરજી કરવી (પગલું-દર-પગલું માર્ગદર્શિકા)',
    aboutMission: 'અમારું લક્ષ્ય',
    aboutText: 'જનસહાય AI નો ઉદ્દેશ ગ્રામીણ અને અર્ધ-શહેરી ભારતમાં માહિતીના અંતરને દૂર કરવાનો છે. સરળ વૉઇસ ઇનપુટ સાથે માતૃભાષામાં માહિતી પૂરી પાડીને, અમે એ સુનિશ્ચિત કરવામાં મદદ કરીએ છીએ કે કોઈ પાત્ર નાગરિક પાછળ રહી ન જાય.',
    feedbackHelpful: 'શું આ જવાબ મદદરૂપ હતો?',
    feedbackThankYou: 'તમારા પ્રતિસાદ માટે આભાર!',
    voicePromptStart: 'સાંભળી રહ્યા છીએ... કૃપા કરીને હવે બોલો.',
    voicePromptStop: 'અવાજ પ્રક્રિયા હેઠળ છે...',
    voiceNotSupported: 'આ બ્રાઉઝરમાં સ્પીચ રેકગ્નિશન સપોર્ટેડ નથી.',
    ttsSpeak: 'સાંભળો (ટેક્સ્ટ ટુ સ્પીચ)',
    ttsStop: 'સાંભળવાનું બંધ કરો',
    thinking: 'વિચારી રહ્યા છીએ, કૃપા કરીને પ્રતિક્ષા કરો...'
  },
  ta: {
    title: 'ஜனசஹாய் AI',
    subtitle: 'அரசு திட்ட உதவியாளர்',
    tagline: 'உங்கள் சொந்த மொழியில் அரசு திட்டங்களைக் கண்டறியவும்',
    searchPlaceholder: 'பெயர், முக்கிய சொல் மூலம் தேடவும் அல்லது கேள்வி கேட்கவும்...',
    browseCategories: 'வகைகளை உலாவுக',
    featuredSchemes: 'சிறப்பு திட்டங்கள்',
    howItWorks: 'இது எவ்வாறு செயல்படுகிறது',
    step1Title: 'AI-யிடம் கேளுங்கள்',
    step1Desc: 'உங்கள் வட்டார மொழியில் உங்கள் கேள்வியைத் தட்டச்சு செய்யவும் அல்லது பேசவும்.',
    step2Title: 'உடனடித் தகவல் பெறுக',
    step2Desc: 'தெளிவான தகுதி விதிகள் மற்றும் ஆவணங்களின் சரிபார்ப்புப் பட்டியலைப் பெறுங்கள்.',
    step3Title: 'அதிகாரப்பூர்வமாக விண்ணப்பிக்கவும்',
    step3Desc: 'விண்ணப்பிக்க நேரடியாக அதிகாரப்பூர்வ அரசு போர்ட்டலுக்குச் செல்லவும்.',
    navHome: 'முகப்பு',
    navBrowse: 'திட்டங்களை உலாவுக',
    navEligibility: 'தகுதியைச் சரிபார்க்கவும்',
    navApplications: 'என் விண்ணப்பங்கள்',
    navDashboard: 'டாஷ்போர்டு',
    navAbout: 'எங்களைப் பற்றி',
    navChat: 'உதவியாளரிடம் கேளுங்கள்',
    login: 'உள்நுழைக',
    signup: 'பதிவு செய்க',
    disclaimer: 'ஜனசஹாய் AI என்பது ஒரு சுயாதீனமான ஓப்பன் சோர்ஸ் திட்டமாகும், இது இந்திய அரசாங்கத்துடன் இணைக்கப்பட்டது அல்லது அங்கீகரிக்கப்பட்டது அல்ல. எப்போதும் அதிகாரப்பூர்வ இணையதளங்களில் விவரங்களைச் சரிபார்க்கவும்.',
    statisticsTitle: 'தளத்தின் தாக்கம்',
    statSchemes: 'மொத்த திட்டங்கள் அட்டவணைப்படுத்தப்பட்டுள்ளன',
    statPortals: 'அதிகாரப்பூர்வ போர்ட்டல்கள்',
    statLanguages: 'ஆதரிக்கப்படும் மொழிகள்',
    allRightsReserved: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    applyNow: 'அதிகாரப்பூர்வ போர்ட்டலில் விண்ணப்பிக்கவும்',
    knowMore: 'மேலும் அறிய',
    source: 'ஆதாரம்',
    relatedSchemes: 'தொடர்புடைய திட்டங்கள்',
    whoQualifies: 'யார் தகுதியுடையவர்கள் (தகுதி)',
    docsNeeded: 'தேவையான ஆவணங்கள்',
    howToApply: 'விண்ணப்பிப்பது எப்படி (படி-படியாக வழிகாட்டி)',
    aboutMission: 'எங்கள் நோக்கம்',
    aboutText: 'ஜனசஹாய் AI கிராமப்புற மற்றும் நகர்ப்புற இந்தியாவிற்கு இடையேயான தகவல் இடைவெளியைக் குறைக்க முயல்கிறது. எளிமையான குரல் உள்ளீட்டுடன் தாய்மொழியில் தகவல்களை வழங்குவதன் மூலம், தகுதியுள்ள குடிமக்கள் யாரும் விடுபடாமல் இருப்பதை உறுதிசெய்ய உதவுகிறோம்.',
    feedbackHelpful: 'இந்த பதில் பயனுள்ளதாக இருந்ததா?',
    feedbackThankYou: 'உங்கள் கருத்துக்கு நன்றி!',
    voicePromptStart: 'கேட்கிறது... தயவுசெய்து இப்போது பேசவும்.',
    voicePromptStop: 'பேச்சு செயலாக்கப்படுகிறது...',
    voiceNotSupported: 'இந்த உலாவியில் பேச்சு அங்கீகாரம் ஆதரிக்கப்படவில்லை.',
    ttsSpeak: 'கேட்கவும் (ஒலி வடிவில்)',
    ttsStop: 'கேட்பதை நிறுத்தவும்',
    thinking: 'சிந்திக்கிறது, தயவுசெய்து காத்திருக்கவும்...'
  },
  te: {
    title: 'జనసహాయ్ AI',
    subtitle: 'ప్రభుత్వ పథకాల సహాయకుడు',
    tagline: 'మీ స్వంత భాషలో ప్రభుత్వ పథకాలను కనుగొనండి',
    searchPlaceholder: 'పేరు, కీవర్డ్ ద్వారా వెతకండి లేదా ప్రశ్న అడగండి...',
    browseCategories: 'విభాగాలను బ్రౌజ్ చేయండి',
    featuredSchemes: 'ముఖ్య పథకాలు',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    step1Title: 'AIని అడగండి',
    step1Desc: 'మీ ప్రాంతీయ భాషలో మీ ప్రశ్నను టైప్ చేయండి లేదా మాట్లాడండి.',
    step2Title: 'తక్షణ సమాచారం పొందండి',
    step2Desc: 'స్పష్టమైన అర్హత నియమాలు మరియు పత్రాల జాబితాను పొందండి.',
    step3Title: 'అధికారికంగా దరఖాస్తు చేసుకోండి',
    step3Desc: 'దరఖాస్తు చేయడానికి నేరుగా అధికారిక ప్రభుత్వ పోర్టల్‌కు వెళ్లండి.',
    navHome: 'హోమ్',
    navBrowse: 'పథకాలు బ్రౌజ్ చేయండి',
    navEligibility: 'అర్హతను తనిఖీ చేయండి',
    navApplications: 'నా దరఖాస్తులు',
    navDashboard: 'డాష్‌బోర్డ్',
    navAbout: 'మా గురించి',
    navChat: 'సహాయకుడిని అడగండి',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    disclaimer: 'జనసహాయ్ AI అనేది స్వతంత్ర ఓపెన్ సోర్స్ ప్రాజెక్ట్ మరియు భారత ప్రభుత్వంతో అనుబంధించబడలేదు లేదా ఆమోదించబడలేదు. ఎల్లప్పుడూ అధికారిక పోర్టల్స్ లో వివరాలను ధృవీకరించుకోండి.',
    statisticsTitle: 'ప్లాట్‌ఫారమ్ ప్రభావం',
    statSchemes: 'మొత్తం ఇండెక్స్ చేసిన పథకాలు',
    statPortals: 'అధికారిక పోర్టల్‌లు',
    statLanguages: 'మద్దతు ఉన్న భాషలు',
    allRightsReserved: 'సర్వ హక్కులు ప్రత్యేకించబడినవి.',
    applyNow: 'అధికారిక పోర్టల్‌లో దరఖాస్తు చేయండి',
    knowMore: 'మరింత తెలుసుకోండి',
    source: 'మూలం',
    relatedSchemes: 'సంబంధిత పథకాలు',
    whoQualifies: 'ఎవరు అర్హులు (అర్హత)',
    docsNeeded: 'కావలసిన పత్రాలు',
    howToApply: 'ఎలా దరఖాస్తు చేయాలి (దశల వారీ గೈడ్)',
    aboutMission: 'మా లక్ష్యం',
    aboutText: 'జనసహాయ్ AI గ్రామీణ మరియు అర్ధ-పట్టణ భారతదేశంలో సమాచార అంతరాన్ని తగ్గించడానికి ప్రయత్నిస్తుంది. సాధారణ వాయిస్ ఇన్‌పుట్‌తో స్థానిక భాషలలో సమాచారాన్ని అందించడం ద్వారా, ఏ అర్హత గల పౌరుడు వెనుకబడిపోకుండా ఉండేలా మేము సహాయం చేస్తాము.',
    feedbackHelpful: 'ఈ సమాధానం ఉపయోగకరంగా ఉందా?',
    feedbackThankYou: 'మీ అభిప్రాయానికి ధన్యవాదాలు!',
    voicePromptStart: 'వింటున్నారు... దయచేసి ఇప్పుడు మాట్లాడండి.',
    voicePromptStop: 'వాయిస్ ప్రాసెస్ అవుతోంది...',
    voiceNotSupported: 'ఈ బ్రౌజర్‌లో వాయిస్ గుర్తింపు మద్దతు లేదు.',
    ttsSpeak: 'వినండి (టెక్స్ట్ టు స్పీచ్)',
    ttsStop: 'వినడం ఆపివేయండి',
    thinking: 'ఆలోచిస్తోంది, దయచేసి వేచి ఉండండి...'
  },
  bn: {
    title: 'জনসহায় AI',
    subtitle: 'সরকারি প্রকল্প সহকারী',
    tagline: 'আপনার নিজের ভাষায় সরকারি প্রকল্প খুঁজুন',
    searchPlaceholder: 'নাম, কীওয়ার্ড দিয়ে খুঁজুন বা প্রশ্ন জিজ্ঞাসা করুন...',
    browseCategories: 'বিভাগগুলি ব্রাউজ করুন',
    featuredSchemes: 'শীর্ষস্থানীয় প্রকল্প',
    howItWorks: 'এটি কীভাবে কাজ করে',
    step1Title: 'AI কে জিজ্ঞাসা করুন',
    step1Desc: 'আপনার আঞ্চলিক ভাষায় আপনার প্রশ্ন টাইপ করুন বা বলুন।',
    step2Title: 'তাত্ক্ষণিক তথ্য পান',
    step2Desc: 'পরিষ্কার যোগ্যতা নীতি এবং প্রয়োজনীয় নথির তালিকা পান।',
    step3Title: 'অফিসিয়ালি আবেদন করুন',
    step3Desc: 'আবেদন করতে সরাসরি অফিসিয়াল সরকারি পোর্টালে যান।',
    navHome: 'হোম',
    navBrowse: 'প্রকল্পগুলি ব্রাউজ করুন',
    navEligibility: 'যোগ্যতা পরীক্ষা করুন',
    navApplications: 'আমার আবেদনসমূহ',
    navDashboard: 'ড্যাশবোর্ড',
    navAbout: 'আমাদের সম্পর্কে',
    navChat: 'সহকারীকে জিজ্ঞাসা করুন',
    login: 'লগ ইন',
    signup: 'সাইন আপ',
    disclaimer: 'জনসহায় AI একটি স্বাধীন ওপেন সোর্স প্রকল্প এবং এটি ভারত সরকারের সাথে অনুমোদিত বা সমর্থিত নয়। সর্বদা অফিসিয়াল পোর্টালে তথ্য যাচাই করুন।',
    statisticsTitle: 'প্ল্যাটফর্মের প্রভাব',
    statSchemes: 'মোট সূচীকৃত প্রকল্প',
    statPortals: 'অফিসিয়াল পোর্টালসমূহ',
    statLanguages: 'সমর্থিত ভাষা সমূহ',
    allRightsReserved: 'সর্বস্বত্ব সংরক্ষিত।',
    applyNow: 'অফিসিয়াল পোর্টালে আবেদন করুন',
    knowMore: 'আরো জানুন',
    source: 'উৎস',
    relatedSchemes: 'সম্পর্কিত প্রকল্পগুলি',
    whoQualifies: 'কারা যোগ্য (যোগ্যতা)',
    docsNeeded: 'প্রয়োজনীয় কাগজপত্র',
    howToApply: 'কীভাবে আবেদন করবেন (ধাপে ধাপে নির্দেশিকা)',
    aboutMission: 'আমাদের লক্ষ্য',
    aboutText: 'জনসহায় AI গ্রামীণ এবং আধা-শহুরে ভারতের তথ্যের ঘাটতি দূর করতে কাজ করছে। সহজ ভয়েস ইনপুট সহ মাতৃভাষায় তথ্য প্রদানের মাধ্যমে, আমরা নিশ্চিত করতে সাহায্য করি যে কোনো যোগ্য নাগরিক বঞ্চিত না হন।',
    feedbackHelpful: 'এই উত্তরটি কি সহায়ক ছিল?',
    feedbackThankYou: 'আপনার প্রতিক্রিয়ার জন্য ধন্যবাদ!',
    voicePromptStart: 'শুনছি... অনুগ্রহ করে এখন বলুন।',
    voicePromptStop: 'ভয়েস প্রক্রিয়া করা হচ্ছে...',
    voiceNotSupported: 'এই ব্রাউজারে ভয়েস সনাক্তকরণ সমর্থিত নয়।',
    ttsSpeak: 'শুনুন (ভয়েসে)',
    ttsStop: 'শোনা বন্ধ করুন',
    thinking: 'ভাবছি, অনুগ্রহ করে অপেক্ষা করুন...'
  },
  mr: {
    title: 'जनसहाय AI',
    subtitle: 'सरकारी योजना सहाय्यक',
    tagline: 'तुमच्या स्वतःच्या भाषेत सरकारी योजना शोधा',
    searchPlaceholder: 'नाव, कीवर्ड द्वारे शोधा किंवा प्रश्न विचारा...',
    browseCategories: 'श्रेणीनुसार ब्राउझ करा',
    featuredSchemes: 'प्रमुख योजना',
    howItWorks: 'हे कसे कार्य करते',
    step1Title: 'AI ला विचारा',
    step1Desc: 'तुमच्या प्रादेशिक भाषेत तुमचा प्रश्न लिहा किंवा बोला.',
    step2Title: 'झटपट माहिती मिळवा',
    step2Desc: 'स्पष्ट पात्रता नियम आणि आवश्यक कागदपत्रांची यादी मिळवा.',
    step3Title: 'अधिकृतपणे अर्ज करा',
    step3Desc: 'अर्ज करण्यासाठी थेट अधिकृत सरकारी पोर्टलवर जा.',
    navHome: 'होम',
    navBrowse: 'योजना ब्राउझ करा',
    navEligibility: 'पात्रता तपासा',
    navApplications: 'माझे अर्ज',
    navDashboard: 'डॅशबोर्ड',
    navAbout: 'आमच्याबद्दल',
    navChat: 'सहाय्यकाला विचारा',
    login: 'लॉग इन',
    signup: 'साइन अप',
    disclaimer: 'जनसहाय AI हा एक स्वतंत्र ओपन-सोर्स प्रकल्प आहे आणि तो भारत सरकारशी संलग्न किंवा समर्थित नाही. अधिकृत पोर्टलवर नेहमी तपशील तपासा.',
    statisticsTitle: 'प्लॅटफॉर्म प्रभाव',
    statSchemes: 'एकूण अनुक्रमित योजना',
    statPortals: 'कव्हर केलेले अधिकृत पोर्टल',
    statLanguages: 'समर्थित भाषा',
    allRightsReserved: 'सर्व हक्क राखीव.',
    applyNow: 'अधिकृत पोर्टलवर अर्ज करा',
    knowMore: 'अधिक जाणून घ्या',
    source: 'स्रोत',
    relatedSchemes: 'संबंधित योजना',
    whoQualifies: 'कोण पात्र आहे (पात्रता)',
    docsNeeded: 'आवश्यक कागदपत्रे',
    howToApply: 'अर्ज कसा करावा (टप्प्याटप्प्याने मार्गदर्शक)',
    aboutMission: 'आमचे ध्येय',
    aboutText: 'जनसहाय AI चा उद्देश ग्रामीण आणि निम-शहरी भारतातील माहितीची दरी कमी करणे आहे. सोप्या व्हॉइस इनपुटसह मातृभाषेत माहिती देऊन, आम्ही कोणताही पात्र नागरिक मागे राहणार नाही याची खात्री करण्यात मदत करतो.',
    feedbackHelpful: 'हे उत्तर उपयुक्त होते का?',
    feedbackThankYou: 'तुमच्या अभिप्रायाबद्दल धन्यवाद!',
    voicePromptStart: 'ऐकत आहे... कृपया आता बोला.',
    voicePromptStop: 'आवाज प्रक्रिया केला जात आहे...',
    voiceNotSupported: 'या ब्राउझरमध्ये व्हॉइस ओळख समर्थित नाही.',
    ttsSpeak: 'ऐका (व्हॉइसमध्ये)',
    ttsStop: 'ऐकणे थांबवा',
    thinking: 'विचार करत आहे, कृपया प्रतीक्षा करा...'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('jansahay_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('jansahay_lang', lang);
  }, [lang]);

  const t = translations[lang] || translations['en'];

  const getLanguageName = (code) => {
    const l = languages.find(item => item.code === code);
    return l ? l.name : code;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, getLanguageName }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
